### ISSUE TITLE
Can't deploy firebase project

### ISSUE THREAD

**Issue by pikilon** [simondotm/nx-firebase#153]
If I run
`firebase deploy` it works perfectly fine

If I run 
`npx nx deploy fire-config`

I have the following error
```bash
> nx run fire-config:firebase deploy
fs.js:42
} = primordials;
    ^
ReferenceError: primordials is not defined
    at fs.js:42:5
```

I also have problems with getConfig because of the runtime file.

**Comment by pikilon** [comment]
> If I run `firebase deploy` it works perfectly fine
> 
> If I run `npx nx deploy fire-config`
> 
> I have the following error
> 
> ```shell
> > nx run fire-config:firebase deploy
> fs.js:42
> } = primordials;
>     ^
> ReferenceError: primordials is not defined
>     at fs.js:42:5
> ```
> 
> I also have problems with getConfig because of the runtime file.

I found the problem: I had an old version of firebase-tools installed and was failing because of that.
